### ISSUE TITLE
rx/tx logic for returning an used-buffer shall be async

### ISSUE THREAD

**Issue by MatiasVara** [virtio-sound/vhost-device#12]
The spec defines that returning a used buffer could be used by the kernel as a notification:

> the completion of such an I/O request can be considered an elapsed period notification.

The buffer shall be returned only after they are consumed so notification shall be delayed. This semantics is different for the control queue in which used-buffers are returned intermediately.

**Comment by stefano-garzarella** [comment]
Already fixed.
