### ISSUE TITLE
sometimes control msgs triggered a timeout in the kernel guest

### ISSUE THREAD

**Issue by MatiasVara** [virtio-sound/vhost-device#13]
I am observing this once every ~ four time I boot a guest. I still do not understand the reason. The timeout is triggered before any msg reaches the control queue.

**Comment by epilys** [comment]
Maybe it'd make sense to not try to make the control/tx queue work since we already have a working solution? This'd speed up things considerably

**Comment by MatiasVara** [comment]
I created this issue to understand the timeout I observe many times when I boot up the guest. This timeout is for the `PCM_GET_INFO` control msg. I remember you talked about a timeout during the weekly but I am afraid I do not understand if it is the same. Is the use of `any` at https://github.com/epilys/vhost-device/blob/81a03fb2935c5016b391f753fc5e65e6c91cface/crates/sound/src/device.rs#L141 related with this?

**Comment by epilys** [comment]
I can't debug your code, sorry.

**Comment by dorindabassey** [comment]
if it helps this issue, I can't reproduce this timeout on my guest, maybe it might be related to the image.

**Comment by stefano-garzarella** [comment]
We are not observing this issue anymore, we will open again upstream if needed.
