### ISSUE TITLE
Wrong buffers queued for playback

### ISSUE THREAD

**Issue by dorindabassey** [virtio-sound/vhost-device#25]
with the current handling of the TX queues, the guest is sending duplicated buffers, you can test this by executing aplay on the guest and you would hear some double sound or incorrect audio. CC'ing @epilys and @MatiasVara

**Comment by dorindabassey** [comment]
#29  has a temporary workaround to fix this

**Comment by MatiasVara** [comment]
This is fixing by #32. I close this issue.
