### ISSUE TITLE
Have Null backend available when compiled with `--no-default-features`

### ISSUE THREAD

**Issue by aesteve-rh** [virtio-sound/vhost-device#26]
Came from a discussion at #24 

When we compile with no default features:
```
cargo build --no-default-feaures
```
We do not have any backend available. As a consequence, many parts of the code are not reachable and may lead
to some potential issues. Also, it does not make much sense to have the daemon with no available backends (as it cannot be used anyway).

I understand that the goal is to avoid the Null backend when another backend is explicitly enabled.
But maybe the bytes saved from the binary do not justify supporting the `no-features` case.

In any case, possible solutions that I can think atm:

- Tweak the `Cargo.toml` file to have `null-backend` set if no other feature is available -> Not sure if possible.
- Fail the compilation if no feature is set -> Better than allowing a wonky executable.
- Have the Null backend always compiled, unconditionally -> Will add some bytes to the binary, but may be worth?

**Comment by stefano-garzarella** [comment]
> In any case, possible solutions that I can think atm:
> 
>     * Tweak the `Cargo.toml` file to have `null-backend` set if no other feature is available -> Not sure if possible.
> 
>     * Fail the compilation if no feature is set -> Better than allowing a wonky executable.
> 
>     * Have the Null backend always compiled, unconditionally -> Will add some bytes to the binary, but may be worth?

I'd go with this. The null backend should really be very small without any dependecy, so could make sense to have always it without any feature.
