### ISSUE TITLE
Remove returning value for process_*() and for handle_event()

### ISSUE THREAD

**Issue by MatiasVara** [virtio-sound/vhost-device#39]
See https://github.com/rust-vmm/vhost/pull/192. 

https://github.com/virtio-sound/vhost-device/blob/cbc80bee229ed0b827d45ef14d3b89d9396d72f8/crates/sound/src/device.rs#L492

**Comment by stefano-garzarella** [comment]
Close this one. When we will switch to the new `vhost` version, we will update all the devices.
